language: ruby
rvm:
  - "2.3"
  - "jruby"
script:
  - bundle exec rake all
notifications:
  email:
    recipients:
      - D&ENewsFrameworksTeam@bbc.co.uk
    on_failure: change
    on_success: never
